include: package:very_good_analysis/analysis_options.6.0.0.yaml
analyzer:
  exclude:
    - build/**
    - "**.freezed.dart"
    - "**.g.dart"
    # - test/**
  errors:
    avoid_dynamic_calls: ignore
    avoid_returning_this: ignore
    avoid_setters_without_getters: ignore
    cascade_invocations: ignore
    eol_at_end_of_file: ignore
    inference_failure_on_function_invocation: ignore
    invalid_annotation_target: ignore
    missing_code_block_language_in_doc_comment: ignore
    no_default_cases: ignore
    one_member_abstracts: ignore
    prefer_null_aware_method_calls: ignore
    use_if_null_to_convert_nulls_to_bools: ignore
    use_setters_to_change_properties: ignore
    use_to_and_as_if_applicable: ignore

linter:
  rules:
    file_names: false
    type_annotate_public_apis: false
    require_trailing_commas: false
    sort_pub_dependencies: false
    avoid_print: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    flutter_style_todos: false
