name: ioredis
description: A high-performance Redis client for Dart with support for pub/sub, JSON operations, Unicode, and bulk operations.
version: 1.1.1
repository: https://github.com/dartondox/ioredis

environment:
  sdk: ^3.1.0

dev_dependencies:
  very_good_analysis: ^9.0.0
  test: any
dependencies:
  collection: ^1.19.0
