name: ioredis
description: Redis driver for dart
version: 1.1.1
repository: https://github.com/dartondox/ioredis

environment:
  sdk: ^3.1.0

dev_dependencies:
  very_good_analysis: ^6.0.0
  test: any
dependencies:
  collection: ^1.19.0
